theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "temperature"
interval = 10

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "net"
device = "wlp58s0"
ip = true
interval = 5
speed_up = false
speed_down = false

[[block]]
block = "cpu"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "battery"
interval = 10
upower = true

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
